### PR TITLE
pt_br.lang - Added credits for all authors

### PR DESCRIPTION
**Pull request by Regnander**
Copied the credits format from the other `.lang` files and checked the commit history to add all authors and their respective commit dates.

### CODE REVIEW

**Comment by Regnander** [comment]
>Hello @Regnander

Howdy @DaDodger

> I believe you should talk to me before proposing any changes in the `pt-br.lang file`

Nope. And if you are trying to impress me with that attitude of yours, you are not succeeding.

> The reason I have deleted Inky1003's signature is due to his unprofessionalism while "translating". 

It's possible that he is younger than you and still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all.
You kept his signature until 24 Dec 2017, which was around two months after his last commit. How come you didn't remove it earlier if you think he isn't worth the credit?

>Do not try to impose a template

I added this "template" because the current format lacked dates and it's nice to see for how long the authors have been working on the translation. I don't see any harm in that.

>in a language file you do not understand.

I don't find this relevant at all, since I wasn't touching the translation itself.

**Comment by DaDodger** [comment]
I really appreciate your delayed reply. Thank you very much.

> [...] And if you are trying to impress me with that attitude of yours, you are not succeeding.

My reply was meant to be sharp at all. You know what? I didn't see your localization manager badge yet.

The thing is that a foreign contributor who does not speak Portuguese is trying to propose changes (does not matter what, it is a change at all) in Brazilian Portuguese language file. If I would open a pull request in Swedish language file - a very rare situation - certainly I would talk to you first, since you are the main contributor there.

I talked to **Inky** prior to his departure. He has allegedly a mental **disorder** that makes him struggle with language. Therefore, I suppose he is quite unqualified to translate one of the most downloaded Minecraft mods.

> [...] And still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all.

Are you saying me that we should keep untouched these severe errors in language files since Minecraft still has a young audience? We are serious translators, aren't we? Let these kids try to translate even a sentence is not much of a professional behaviour.

**Comment by DaDodger** [comment]
@Regnander I really appreciate your delayed reply. Thank you very much.

> Nope. And if you are trying to impress me with that attitude of yours, you are not succeeding.

My response was meant to be sharp at all. I haven't see your localisation manager badge yet.

The thing is that a foreign contributor who does not speak Brazilian Portuguese is attempting to propose a change (does not matter what, it is a change at all) in Portuguese language file. If I would open a pull request in Swedish language file - a very rare situation - I would certainly talk to you first, since you are the main contributor there.

Months ago, I talked to **Inky3001** via Discord prior to his leaving. He allegedly has a mental **disorder** that makes him struggle with language. Consequently, I suppose he is quite unqualified to translate one of the most downloaded Minecraft mods.

> [...] And still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all. 

Are you saying me that we should permit an unskilled kid try to translate an entire file filled with special terminology concerning computer science? I did not remove his signature immediately because I had to translate again the file in separated pull requests in last six months.

Inky3001 does not deserve any bit of credit since he made a complete mess using Google Translate. GuilhermeDiasJ, a fellow Minecraft proofreader, and I are now in charge of the pt_br.lang. Do not please interfere in a foreign language file without invitation or necessity.

**Comment by DaDodger** [comment]
@Regnander I really appreciate your delayed reply. Thank you very much.

> Nope. And if you are trying to impress me with that attitude of yours, you are not succeeding.

My response was meant to be sharp at all. I haven't see your localisation manager badge yet.

The thing is that a foreign contributor who does not speak Brazilian Portuguese is attempting to propose a change (does not matter what, it is a change at all) in Portuguese language file. If I would open a pull request in Swedish language file - a very rare situation - I would certainly talk to you first, since you are the main contributor there.

Months ago, I talked to **Inky3001** via Discord prior to his leaving. He allegedly has a mental **disorder** that makes him struggle with language. Consequently, I suppose he is quite unqualified to translate one of the most downloaded Minecraft mods.

> [...] And still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all. 

Are you saying me that we should permit an unskilled kid try to translate an entire file filled with special terminology concerning computer science? I did not remove his signature immediately because I had to translate again the file in separated pull requests in last six months.

Inky3001 does not deserve a bit of credit since he made a complete mess using Google Translate. GuilhermeDiasJ, a fellow Minecraft proofreader, and I are now in charge of the `pt_br.lang`. Do not please interfere in a foreign language file without invitation or necessity.

**Comment by DaDodger** [comment]
@Regnander I really appreciate your delayed reply. Thank you very much.

> Nope. And if you are trying to impress me with that attitude of yours, you are not succeeding.

My response was meant to be sharp at all. I haven't see your localisation manager badge yet.

The thing is that a foreign contributor who does not speak Brazilian Portuguese is attempting to propose a change (does not matter what, it is a change at all) in Portuguese language file. If I would open a pull request in Swedish language file - a very rare situation - I would certainly talk to you first, since you are the main contributor there.

Months ago, I talked to **Inky1003** via Discord prior to his leaving. He allegedly has a mental **disorder** that makes him struggle with language. Consequently, I suppose he is quite unqualified to translate one of the most downloaded Minecraft mods.

> [...] And still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all. 

Are you saying me that we should permit an unskilled kid try to translate an entire file filled with special terminology concerning computer science? I did not remove his signature immediately because I had to translate again the file in separated pull requests in last six months.

Inky1003 does not deserve a bit of credit since he made a complete mess using Google Translate. GuilhermeDiasJ, a fellow Minecraft proofreader, and I are now in charge of the `pt_br.lang`. Do not please interfere in a foreign language file without invitation or necessity.

**Comment by DaDodger** [comment]
@Regnander I really appreciate your delayed reply. Thank you very much.

> Nope. And if you are trying to impress me with that attitude of yours, you are not succeeding.

My response was meant to be sharp at all. I haven't see your localisation manager badge yet.

The thing is that a foreign contributor, who does not speak Brazilian Portuguese, is attempting to propose a change (does not matter what, it is a change at all) in Portuguese language file. If I would open a pull request in Swedish language file - a very rare situation - I would certainly talk to you first, since you are the main contributor there.

Months ago, I talked to **Inky1003** via Discord prior to his leaving. He allegedly has a mental **disorder** that makes him struggle with language. Consequently, I suppose he is quite unqualified to translate one of the most downloaded Minecraft mods.

> [...] And still has some flaws to iron out in his grammar and spelling. Minecraft has a pretty young main audience, after all. 

Are you saying me that we should permit an unskilled kid try to translate an entire file filled with special terminology concerning computer science? I did not remove his signature immediately because I had to translate again the file in separated pull requests in last six months.

Inky1003 does not deserve a bit of credit since he made a complete mess using Google Translate. GuilhermeDiasJ, a fellow Minecraft proofreader, and I are now in charge of the `pt_br.lang`. Do not please interfere in a foreign language file without invitation or necessity.

**Comment by Regnander** [comment]
>My response was meant to be sharp at all.

(I suppose you made a typo here and this is supposed to be "wasn't meant")
But is sure sounded sharp. Well, I'm glad this misunderstanding was cleared out...

>I really appreciate your delayed reply. Thank you very much.

...but there is an underlying tone of sarcasm here.

>I haven't see your localisation manager badge yet.

I don't have one and I don't really mind not having one. Why did you suddenly bring that up?

>The thing is that a foreign contributor, who does not speak Brazilian Portuguese, is attempting to propose a change (does not matter what, it is a change at all) in Portuguese language file.

So this is why you are so protective of it. I get your point.

>Months ago, I talked to Inky1003 via Discord prior to his leaving. He allegedly has a mental disorder that makes him struggle with language.

Okay, that explains the errors you mentioned. Poor guy.

>Are you saying me that we should permit an unskilled kid try to translate an entire file filled with special terminology concerning computer science?

My point is that he should at least get credit if the language file contains some of his work.

>I did not remove his signature immediately because I had to translate again the file in separated pull requests in last six months.

Did you delete Inky's translation and translated the file from scratch? If that's the case, then I'm fine with you being the lone person in the credits section and I can close this pull request. (Although, it still would be nice to add the dates...)

>GuilhermeDiasJ, a fellow Minecraft proofreader, and I are now in charge of the `pt_br.lang`.

I've seen him on Crowdin. That sassy Bowser avatar is not something you easily forget.

**Comment by DaDodger** [comment]
Hello @Regnander

To tell you the truth, looking back, I'm awfully sorry for sounding that harsh. Not in the best mood nowadays.

> (I suppose you made a typo here and this is supposed to be "wasn't meant")

Yeah. It was supposed to be "wasn't meant”.

> ...but there is an underlying tone of sarcasm here.

I apologise again for getting triggered at the beginning of this discussion.

> Did you delete Inky's translation and translated the file from scratch? If that's the case, then I'm fine with you being the lone person in the credits section and I can close this pull request. 

Yes. In fact, there were so many mistakes that I had to download the file and translate it all over and over and over using Visual Studio Code. Seven months ago, the file was stuck with each and every type of mistake. For instance:

_How did "Aniso-" turn out to be "Ansil-"*?_

Source: Anisotropic (n.)
Inky’s translation: Ansiltrópica*
Grammatical: Anisotrópica

It’s an odd typo 🤔

Another example: _The stress on the incorrect syllable in Portuguese._

Source: Subtle (adj.)
Inky’s translation: Sútil*
Grammatical: Sutil

I've never met a Lusophone person in my entire life who writes “sútil” instead of “sutil”. The diacritic `´` changes the phonemic value of “su”, then the tonic syllable is “sú” (with raising intonation) instead of “til”, the correct one. In a nutshell, “sútil” and “sutil” are distinct words.

> (Although, it still would be nice to add the dates...)

Let's try to reach an agreement. You're right. Adding dates is important to 👀 easily commits history. In the next pull requests, I will surely include the dates in credits section. Once more, I’m sorry for getting bothered. Peace.

= *ungrammatical

**Comment by Regnander** [comment]
>Yes. In fact, there were so many mistakes that I had to download the file and translate it all over and over and over using Visual Studio Code. Seven months ago, the file was stuck with each and every type of mistake.

Okay, in that case I'm gonna close this commit now.

>Let's try to reach an agreement. You're right. Adding dates is important to :eyes: easily commits history. In the next pull requests, I will surely include the dates in credits section.

Neat! Thank you.

>To tell you the truth, looking back, I'm awfully sorry for sounding that harsh. Not in the best mood nowadays.
>Once more, I’m sorry for getting bothered.

I accept your apology.

**Pull request closed without merging**
