### PR TITLE
Create no_no.lang

### PR DESCRIPTION
**Pull request by Thesevs**
Translations coming soon...

### CODE REVIEW

**Comment by Regnander** [comment]
There is already a pull request for no_no at #1630. You can suggest improvements there.

**Comment by DaDodger** [comment]
@Regnander Wait, both #1642 and #1630 are translations of the same language variant? The author of #1630 says it's a reviewed translation for Norwegian Bokmal (nb).

**Comment by Regnander** [comment]
@DaDodger nb_no used to be Norwegian Bokmål up until 1.5 when it was changed to no_no.

**Comment by sp614x** [comment]
Conflicts

**Pull request closed without merging**
