### PR TITLE
Create pt_pt.lang

### PR DESCRIPTION
**Pull request by D3W10**

### CODE REVIEW

**Comment by Regnander** [comment]
@DaDodger Is there a lot of changes that needs to be done in order for it to pass as a European Portuguese translation?

**Comment by DaDodger** [comment]
@Regnander Yeah, a lot of them. Brazilian Portuguese is quite different from European variant regarding to grammar and vocabulary.

**Comment by sp614x** [comment]
Can this be merged as it is now?

**Comment by DaDodger** [comment]
@sp614x No. It should be closed because it's not a reliable translation, just a copy of pt_br.lang.

**Pull request closed without merging**
