### PR TITLE
en_us typo fixed

### PR DESCRIPTION
**Pull request by ichbineinNerd**

### CODE REVIEW

**Comment by TheHADILP** [comment]
Nothing is changed here?

**Comment by ichbineinNerd** [comment]
oh... I wanted to do this:

**Comment by Regnander** [comment]
This spelling is common for some programmers as there are guidelines for naming code stuff, although different programming languages have different guidelines. Here's [Microsoft's](https://msdn.microsoft.com/en-us/library/141e06ef(v=vs.71).aspx) and [Oracle's guidelines](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf) if you want something to read in your spare time. Heck, there is even [a whole Wikipedia article about this](https://en.wikipedia.org/wiki/Naming_convention_(programming)#Letter_case-separated_words)).

Minecraft is even using this spelling in-game:

tooltip

**Comment by sp614x** [comment]
The label "Id" is also used by vanilla, so it should be OK.

**Pull request closed without merging**
