### PR TITLE
Re-amend and add List of Contributors for Chinese language file

### PR DESCRIPTION
**Pull request by muink**

### CODE REVIEW

**Comment by sp614x** [comment]
Why are you removing the translation for some keys (of.general.custom, of.general.from, ...)?

**Comment by muink** [comment]
@sp614x Hum.. That seems to be ignored when i manually merging :o
`custom` to `自定义`
and
`from` to `从` is accurate

**Comment by sp614x** [comment]
Also "of.shaders.profile", please fix it.

**Comment by muink** [comment]
Also I'd like to ask a question
```
of.general.custom=Custom
of.general.from=From
of.shaders.profile=Profile
```
these keys are debug information?  ⊙.⊙
I not have find them in any GUI  \`<_\`

**Comment by sp614x** [comment]
- of.general.custom - is used for the shader profile option when no profile is matching
- of.general.from - is used in shader option tooltips to show in which shader file the option is used
- of.shaders.profile - is the shader profile option
To see them you have to install a shader pack which has a profile configuration and go into Shaders -> Shader Options

**Comment by muink** [comment]
Oh I know it now,Thank you for your answer :-)
Translation is no problem now :+1:

**Comment by muink** [comment]
It can be merging?

**Pull request merged**
