### PR TITLE
Specify telemetry is sent to Mojang

### PR DESCRIPTION
**Pull request by ewanhowell5195**
People could have confused it with being sent to OptiFine instead of Mojang

### CODE REVIEW

**Comment by LapisDemon** [comment]
Is it really _Mojang_ though?
I'm sure sp614x would know way way better than I ever could, but as far as I'm aware, all Mojang servers are or won't be anymore, but even _if_ they were, you login via your **XBOX** account, and telemetry is taken by **MiCROSOFT**.
They have to maintain their services after all.

Personally, I'd find it wrong to mention _Mojang_ in this place, as it'd imo also give people the wrong assumption, that they are not dealing with actually **MICROSOFT**, but still _Mojang_.

**Comment by ewanhowell5195** [comment]
It is Mojang that collect the telemetry.

**Comment by LapisDemon** [comment]
> It is Mojang that collect the telemetry.

Could you give me the source please?
I've heard otherwise.

**Comment by ewanhowell5195** [comment]
https://www.minecraft.net/es-es/article/minecraft-snapshot-21w38a

**Comment by LapisDemon** [comment]
> https://www.minecraft.net/es-es/article/minecraft-snapshot-21w38a

I'm familiar with that old snapshot post, they didn't even mentiont he XUID taken when you login, so I don't feel it's a trustworthy, as not fully transparent, source.

No idea how it looks like on the server side, but I would very much wonder if the user data - incl. the unique identifier, XUID - would not be eventually at least be sent to MICROSOFT / USA servers.

Mojang is MICROSOFT's subsidiary, but it does make a difference whether or not the nonanonymized user data leaves the EU or is being touched/looked at in the EU, or if it travels to USA and is stored or used there.

If I go by MICROSOFT's services agreement as well as XBOX ToS, I'm under the impression that MCJE user data, also of EU users, is being handled in the USA and by MICROSOFT.

No idea if the data is temporarily stored on Swedish or EU servers to comply with GDPR or whatever restrictions MICROSOFT might have.

But I'm not convinced MICROSOFT wouldn't get their hands at all on that user data, just Mojang.

**Comment by LapisDemon** [comment]
Looks like the Java Client Telemetry goes to api.minecraftservices.com.

Server seems to be in the US, but it seems to be AWS, Amazon.. cloudfront.net is Amazon, to my knowledge, hence unsure if MS or Mojang controls it.

I know Mojang also still hosts some things on amazonaws, some old MCJE files, so it might be that the server showing up in telemetry is still Mojang, however, as MS' subsidiary, they will of course also send that data to MICROSOFT in the USA.

But either way, you can assume it goes to at least both, at least currently, and things like servers can change as soon as MS might disable Mojang servers (unless needed as inbetween-step to comply with EU privacy legislation, e.g. GDPR).

So the readings you currently get from telmetry doesn't mean it'd always be the case, as MS might rather use their own servers instead after the sunsetting phase.

**Comment by ewanhowell5195** [comment]
Mojang is owned by microsoft, the data goes to mojang so they can help improve game performance. any data mojang get microsoft can clearly get too since they own them. There is no point saying micosoft when its mojang directly collecting the data. and by saying mojang that is also saying microsoft as they are the parent company. you are just overcomplicating something that didnt need to be overcomplicated. this change was made just so people dont think optifine is collecting the data.

**Comment by LapisDemon** [comment]
> Mojang is owned by microsoft, the data goes to mojang so they can help improve game performance. 
I've never bought the "solely to help game performance" narrative, and that for a very good reason.

> this change was made just so people dont think optifine is collecting the data.
I get that, and that's absolutely good and needed and okay.

> you are just overcomplicating something that didnt need to be overcomplicated.
From your perspective, I accept that, however, not from everyone's.

This topic is very complex, Mojang being subsidiary or not, people perceive Mojang itself differently than MS, but that would lead to far for this issue.

Take care!

**Pull request merged**
