### PR TITLE
Update zh_cn.lang: adjustments and few fixes, add Render Regions

### PR DESCRIPTION
**Pull request by HeartyYF**
https://github.com/sp614x/optifine/blob/c06425999090b26f69278ea3d38208518198d1b6/OptiFineDoc/assets/minecraft/optifine/lang/en_us.lang#L447
https://github.com/sp614x/optifine/blob/c06425999090b26f69278ea3d38208518198d1b6/OptiFineDoc/assets/minecraft/optifine/lang/en_us.lang#L598

Are they contradictory?

### CODE REVIEW

**Comment by HeartyYF** [comment]
I mean...
If I switched off "Rain" and keep the "Rain Splash" on, or vice versa, or some else, how will minecraft perform?

**Comment by HeartyYF** [comment]
@LTSMaker Thanks for constructive suggestions!

**Comment by liach** [comment]
@heartyyf 你在curseforge推广群吗(地球标准的)

**Comment by HeartyYF** [comment]
@liach 不在呀。。还有你之前找我干嘛ww

**Comment by liach** [comment]
好奇而已

**Pull request merged**
